### ISSUE TITLE
install mocha fails

### ISSUE THREAD

**Issue by PPoliakoff** [camerenisonfire/p5-electron-quick-start#1]
When I tried to perform the `npm install` I got many errors. I was able to avoid them by removing mocha from the dependencies.

**Comment by camerenisonfire** [comment]
Hi PPoliakoff,

Thanks for pointing this out. I just tried it and got an error as well. I found es-abstract@1.14.0 was throwing a 404 Not Found. I simply removed the package-lock.json and had npm install create an updated version.
